Refactor Excel Logic
EntryDSM/PrintAdmissionTicket pull request #8
Opened 2020-10-04 16:02 UTC by SangminOut

handler에서 excel 관련 컨텍스트를 가지지 않음 excel관련 로직은 다 excel module package로 이동
data 입력할 cell position 구하는 로직을 일반화 시키도록 수정

2020-10-05 01:26 UTC, LumpKim requested changes
일반화를 거치니 코드가 매우 깔끔해졌네요! 감사합니다
conversation 답변 부탁드려요~

2020-10-05 01:26 UTC, LumpKim commented on excel/excel.go
> +		// NOTE: 왜 col == 1 일 때만 yScale이 다른지 확인
col == 1일 경우 이미지 사이즈가 다른 열보다 크게 지정되는 현상이 있어 1열만 별도로 조치한 것입니다.
excelize 이슈로 보이며, 1열의 값 또한 무작위 대입을 통해 알아낸 것으로 조건문 분기가 필요합니다.
수정 없이 출력을 시도해 보면 1열의 이미지만 비대한 현상을 확인할 수 있습니다.

2020-10-05 01:26 UTC, LumpKim commented on handler/handler.go
> -				}
페이지가 추가(수험표 9개)될 때마다 row를 1칸씩 증가시켜야 페이지 밀림 현상을 방지할 수 있습니다.

2020-10-05 01:26 UTC, LumpKim commented on excel/excel.go
> +		user := users[index-1]
index를 0으로 초기화했으므로 `users[index-1]`를 `users[index]`로 수정해야 한다고 생각합니다.

2020-10-09 13:46 UTC, SangminOut commented on excel/excel.go
> +		user := users[index-1]
76b929f 에서 수정했습니다.

2020-10-09 13:49 UTC, SangminOut commented on handler/handler.go
> -				}
아하 템플릿을 보니 9개 하고 empty라인이 있군요 row 식을 수정했습니다.
b9e8972

2020-10-09 13:53 UTC, SangminOut commented on excel/excel.go
> +		// NOTE: 왜 col == 1 일 때만 yScale이 다른지 확인
아하 6fae9af 에서 수정했습니다.

2020-10-14 23:43 UTC, LumpKim approved these changes

2020-10-14 23:45 UTC, LumpKim commented
- `./cache` 디렉터리가 없는 경우 `os.Mkdir`을 이용해 디렉터리를 생성해주는 로직
- 파일 확장자가 대문자인 경우 이미지를 로드할 수 없는 버그
- 다음 페이지 내용이 없는 경우 이하 내용을 삭제하는 로직
의 추가 구현이 필요합니다. 병합된 후 다른 브랜치에서 수정하도록 하겠습니다.

2020-10-15 02:27 UTC, merged